# Welcome to Jekyll!
#

# Site settings
title: "Rolando Salsa & Orquesta"
description: |
  Site web de Rolando Salsa & Orquesta
owner: "Rolando Salsa & Orquesta"
first_published: 2016 # if migrating another site, the year of your first publish
email: contact@rolandosalsa.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rolandosalsa.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/orquestarolando
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://www.facebook.com/Rolando-Salsa-Orquesta-605765546193608/
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: "mailto:contact@rolandosalsa.com"
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/channel/UCQDWbuvv5mvkLv55Qsak-ig
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

gems:
  - jekyll-polyglot
languages: ["fr", "en", "es"]
default_lang: "fr"
exclude_from_localization: ["audio", "css", "fonts", "images", "js"]
parallel_localization: true

exclude:
  - upload.sh
  - login.sh
  - LICENSE.txt
  - README.txt
